[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nginx"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[phases.build]
cmds = [
    "mkdir -p /var/log/nginx /var/cache/nginx",
    "php artisan storage:link || true",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "mkdir -p /var/log/nginx /var/cache/nginx && (php-fpm -y /assets/php-fpm.conf & nginx -c /assets/nginx.template.conf)"